---
# The main jobs are configured in the "component config", these are additional non-pack jobs

## Async support
- name: redis
  image: tool-containers/redis:latest
  command: server
  continuous: true
  port: 6379

## Backups
- name: backup-database
  command: bash -c 'mkdir -p {{ tool_dir }}/mysql_backups/ && mysqldump -h $TOOL_DB_HOST -u $TOOL_DB_USER -p$TOOL_DB_PASSWORD $TOOL_DB_SCHEMA | gzip -9 > {{ tool_dir }}/mysql_backups/$(date +"%Y%m%dT%H%M%S").sql.gz'
  image: mariadb
  schedule: '45 */2 * * *'
  no-filelog: true
  mount: all

- name: prune-backups
  command: bash -c 'find "{{ tool_dir }}/mysql_backups" -mtime +3 -delete'
  image: bookworm
  schedule: '30 5 * * *'
  no-filelog: true
  mount: all
