---
# Until `port_protocol` is supported in components (T401994)
- name: irc-relay
  image: tool-cluebotng-review/irc-relay:latest
  command: run-relay
  continuous: true
  cpu: '0.5'
  mem: 1Gi
  port: 3334/udp
  replicas: 1
  mount: none

# Extra jobs we run, beyond those directly related to the interface
- name: backup-database
  command: bash -c 'mkdir -p {{ tool_dir }}/mysql_backups/ && mysqldump -h $TOOL_DB_HOST -u $TOOL_DB_USER -p$TOOL_DB_PASSWORD $TOOL_DB_SCHEMA | gzip -9 > {{ tool_dir }}/mysql_backups/$(date +"%Y%m%dT%H%M%S").sql.gz'
  image: mariadb
  schedule: '45 */2 * * *'
  no-filelog: true
  mount: all

- name: prune-backups
  command: bash -c 'find "{{ tool_dir }}/mysql_backups" -mtime +3 -delete'
  image: bookworm
  schedule: '30 5 * * *'
  no-filelog: true
  mount: all
