---
# The primary process (interface) runs as a "web service" which is separate from a "job",
# see `service.template` for the equivalent settings for the web interface.
#
# Here are the "backend" jobs, both scheduled (aka cron jobs) and worker (celery).
#

# Async support

## Redis instance
- name: redis
  image: tool-containers/redis:latest
  command: server
  continuous: true
  port: 6379

## Celery worker
- name: celery-worker
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  command: run-celery
  continuous: true

# Helper services
- name: irc-relay
  image: '{{ image_namespace }}/{{ image_tag_irc_relay }}:latest'
  command: run-relay
  continuous: true
  cpu: '0.5'
  mem: 1Gi
  port: 3334
  replicas: 1
  mount: none

- name: celery-flower
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  command: run-flower
  port: 5001
  health-check-http: /healthcheck
  continuous: true

- name: grafana-alloy
  image: '{{ image_namespace }}/{{ image_tag_grafana_alloy }}:latest'
  command: run-alloy
  continuous: true
  cpu: '0.5'
  mem: 1Gi
  port: 8118
  health-check-http: /health
  mount: all

# Scheduled jobs

## Core jobs
- name: export-statistics
  command: launcher ./manage.py export_statistics
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '13 9 * * *'

- name: update-edit-classifications
  command: launcher ./manage.py update_edit_classification
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '30 */2 * * *'

## Seed jobs
- name: add-reported-edits
  command: launcher ./manage.py add_reported_edits
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '55 * * * *'

- name: add-edits-to-queue
  command: launcher ./manage.py add_edits_to_queue
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '13 6 * * *'

## Helper jobs
- name: add-reviews-from-report
  command: launcher ./manage.py add_reviews_from_report
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '15 * * * *'

- name: add-reviews-from-huggle
  command: launcher ./manage.py add_reviews_from_huggle
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '23 */2 * * *'

## Back-fill jobs
- name: import-training-data
  command: launcher ./manage.py import_training_data
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '15 2 * * *'

- name: mark-edits-as-deleted
  command: launcher ./manage.py mark_edits_as_deleted
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '13 4 * * *'

- name: mark-edits-as-having-data
  command: launcher ./manage.py mark_edits_with_training_data
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '13 3 * * *'

- name: add-dangling-edits-to-group
  command: launcher ./manage.py add_dangling_edits_to_group
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '13 21 * * *'

## Management jobs
- name: cleanup-user-records
  command: launcher ./manage.py cleanup_user_records
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '13 1 * * *'

- name: grant-review-access-from-wikipedia-rights
  command: launcher ./manage.py grant_review_access_from_rights
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '27 * * * *'

# Extra jobs we run, beyond those directly related to the interface

## Backups
- name: backup-database
  command: bash -c 'mkdir -p {{ tool_dir }}/mysql_backups/ && mysqldump -h $TOOL_DB_HOST -u $TOOL_DB_USER -p$TOOL_DB_PASSWORD $TOOL_DB_SCHEMA | gzip -9 > {{ tool_dir }}/mysql_backups/$(date +"%Y%m%dT%H%M%S").sql.gz'
  image: mariadb
  schedule: '45 */2 * * *'
  no-filelog: true
  mount: all

- name: prune-backups
  command: bash -c 'find "{{ tool_dir }}/mysql_backups" -mtime +3 -delete'
  image: bookworm
  schedule: '30 5 * * *'
  no-filelog: true
  mount: all
