---
# The primary process (interface) runs as a "web service" which is separate from a "job",
# see `service.template` for the equivalent settings for the web interface.
#
# Here are the "backend" jobs, both scheduled (aka cron jobs) and worker (celery).
#

# Async support

## Redis instance
- name: redis
  image: tool-containers/redis:latest
  command: server
  continuous: true
  port: 6379

## Celery worker
- name: celery-worker
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  command: run-celery
  continuous: true

# Helper services
- name: irc-relay
  image: '{{ image_namespace }}/{{ image_tag_irc_relay }}:latest'
  command: run-relay
  continuous: true
  cpu: '0.5'
  mem: 1Gi
  port: 3334
  replicas: 1
  mount: none

# Scheduled jobs

## Core jobs
- name: export-statistics
  command: ./manage.py export_statistics
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '13 9 * * *'

- name: update-edit-classifications
  command: ./manage.py update_edit_classification
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '30 */2 * * *'

## Seed jobs
- name: add-reported-edits
  command: ./manage.py add_reported_edits
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '55 * * * *'

- name: add-edits-to-queue
  command: ./manage.py add_edits_to_queue
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '13 6 * * *'

## Helper jobs
- name: add-reviews-from-report
  command: ./manage.py add_reviews_from_report
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '15 * * * *'

- name: add-reviews-from-huggle
  command: ./manage.py add_reviews_from_huggle
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '23 */2 * * *'

## Back-fill jobs
- name: import-training-data
  command: ./manage.py import_training_data
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '15 2 * * *'

- name: update-edit-deletion
  command: ./manage.py update_edit_deletion
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '13 4 * * 1'

## Management jobs
- name: cleanup-user-records
  command: ./manage.py cleanup_user_records
  image: '{{ image_namespace }}/{{ image_tag_reviewer }}:latest'
  schedule: '13 1 * * *'

# Extra jobs we run, beyond those directly related to the interface

## Backups
- name: backup-database
  command: bash -c 'mkdir -p {{ tool_dir }}/mysql_backups/ && mysqldump --defaults-file={{ tool_dir }}/replica.my.cnf -h tools-db {{ database_user }}__reviewer | gzip -9 > {{ tool_dir }}/mysql_backups/$(date +"%Y%m%dT%H%M%S").sql.gz'
  image: mariadb
  schedule: '45 */2 * * *'
  filelog: true
  mount: all
  filelog-stdout: logs/backup-database.stdout.log
  filelog-stderr: logs/backup-database.stderr.log

- name: prune-backups
  command: bash -c 'find "{{ tool_dir }}/mysql_backups" -mtime +3 -delete'
  image: bookworm
  schedule: '30 5 * * *'
  filelog: true
  mount: all
  filelog-stdout: logs/prune-backups.stdout.log
  filelog-stderr: logs/prune-backups.stderr.log
