# Generated by Django 5.2.4 on 2025-07-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cbng_reviewer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_bot",
            field=models.BooleanField(default=False),
        ),
    ]
