# Generated by Django 5.2.4 on 2025-07-26 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cbng_reviewer", "0002_user_is_bot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingdata",
            name="edit",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="cbng_reviewer.edit"),
        ),
        migrations.AddConstraint(
            model_name="classification",
            constraint=models.UniqueConstraint(fields=("edit", "user"), name="unique_edit_user"),
        ),
        migrations.AddConstraint(
            model_name="revision",
            constraint=models.UniqueConstraint(fields=("edit", "type"), name="unique_edit_type"),
        ),
    ]
