# Generated by Django 5.2.4 on 2025-07-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbng_reviewer", "0004_alter_trainingdata_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default="2025-01-01 00:00"),
            preserve_default=False,
        ),
    ]
