# Generated by Django 5.2.4 on 2025-07-28 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbng_reviewer", "0005_classification_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="editgroup",
            name="group_type",
            field=models.IntegerField(
                choices=[(0, "Generic"), (1, "Reported False Positives"), (2, "Training"), (3, "Trial")], default=0
            ),
        ),
        migrations.AddField(
            model_name="editgroup",
            name="related_to",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="cbng_reviewer.editgroup"
            ),
        ),
    ]
