# Generated by Django 5.2.4 on 2025-07-28 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbng_reviewer", "0006_editgroup_group_type_editgroup_related_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editgroup",
            name="related_to",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="cbng_reviewer.editgroup"
            ),
        ),
        migrations.AddConstraint(
            model_name="editgroup",
            constraint=models.UniqueConstraint(fields=("name", "related_to"), name="unique_contextual_name"),
        ),
    ]
