# Generated by Django 5.2.4 on 2025-07-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbng_reviewer", "0007_alter_editgroup_related_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editgroup",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
