# Generated by Django 5.2.4 on 2025-08-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbng_reviewer", "0008_alter_editgroup_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingdata",
            name="comment",
            field=models.TextField(null=True),
        ),
    ]
