# Generated by Django 5.2.4 on 2025-08-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbng_reviewer", "0009_alter_trainingdata_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="edit",
            old_name="deleted",
            new_name="is_deleted",
        ),
    ]
