# Generated by Django 5.2.4 on 2025-08-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbng_reviewer", "0010_rename_deleted_edit_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="edit",
            name="has_training_data",
            field=models.BooleanField(default=False),
        ),
    ]
