# Generated by Django 5.2.4 on 2025-08-06 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbng_reviewer", "0011_edit_has_training_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("minor", models.BooleanField()),
                ("timestamp", models.IntegerField()),
                ("text", models.BinaryField()),
                ("edit", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="cbng_reviewer.edit")),
            ],
        ),
        migrations.CreateModel(
            name="PreviousRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("minor", models.BooleanField()),
                ("timestamp", models.IntegerField()),
                ("text", models.BinaryField()),
                ("edit", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="cbng_reviewer.edit")),
            ],
        ),
    ]
