# Generated by Django 5.2.4 on 2025-08-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbng_reviewer", "0012_currentrevision_previousrevision"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Revision",
        ),
    ]
