# Generated by Django 5.2.4 on 2025-09-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbng_reviewer", "0013_delete_revision"),
    ]

    operations = [
        migrations.RenameField(
            model_name="currentrevision",
            old_name="minor",
            new_name="is_minor",
        ),
        migrations.RenameField(
            model_name="previousrevision",
            old_name="minor",
            new_name="is_minor",
        ),
        migrations.AddField(
            model_name="currentrevision",
            name="is_creation",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
