# Generated by Django 5.2.4 on 2025-09-07 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbng_reviewer", "0014_rename_minor_currentrevision_is_minor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="edit",
            name="last_updated",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="edit",
            name="number_of_agreeing_reviewers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="edit",
            name="number_of_reviewers",
            field=models.IntegerField(default=0),
        ),
    ]
