# Generated by Django 5.2.6 on 2025-11-05 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbng_reviewer", "0015_edit_last_updated_edit_number_of_agreeing_reviewers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reverted", models.FloatField(null=True)),
                ("training", models.FloatField(null=True)),
                ("edit", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="cbng_reviewer.edit")),
            ],
        ),
    ]
