# Generated by Django 5.2.8 on 2026-02-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbng_reviewer", "0015_edit_last_updated_edit_number_of_agreeing_reviewers_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="edit",
            index=models.Index(fields=["status"], name="cbng_review_status_1bd49a_idx"),
        ),
        migrations.AddIndex(
            model_name="edit",
            index=models.Index(fields=["is_deleted"], name="cbng_review_is_dele_a29323_idx"),
        ),
        migrations.AddIndex(
            model_name="edit",
            index=models.Index(fields=["has_training_data"], name="cbng_review_has_tra_a4d5c5_idx"),
        ),
    ]
