# Generated by Django 5.2.8 on 2026-03-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbng_reviewer", "0016_edit_cbng_review_status_1bd49a_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="edit",
            index=models.Index(fields=["is_deleted", "status"], name="cbng_review_is_dele_b35f1f_idx"),
        ),
    ]
