# Generated by Django 5.2.13 on 2026-06-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbng_reviewer", "0018_clienterror"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="clienterror",
            new_name="cbng_review_user_id_92b058_idx",
            old_name="cbng_review_user_id_clienterror_idx",
        ),
        migrations.RenameIndex(
            model_name="clienterror",
            new_name="cbng_review_created_a8dfe0_idx",
            old_name="cbng_review_created_clienterror_idx",
        ),
    ]
