name: CI
on: { pull_request: { }, push: { } }
concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  tox:
    strategy:
      fail-fast: false
      matrix:
        target: [ "ruff", "djlint", "bandit", "test", "black" ]
    runs-on: ubuntu-latest
    continue-on-error: true

    services:
      selenium:
        image: ${{ matrix.target == 'test' && 'selenium/standalone-chrome' || '' }}
        options: --shm-size=2gb

      mysql:
        image: ${{ matrix.target == 'test' && 'mariadb' || '' }}
        env: { "MARIADB_ALLOW_EMPTY_ROOT_PASSWORD": "1" }
        ports: [3306:3306]

      redis:
        image: ${{ matrix.target == 'test' && 'redis' || '' }}
        ports: [6379:6379]

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
          cache: 'pip'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Install python dependencies
        run: poetry install --with test

      - name: Generate config
        run: |
          cat > config.yaml <<'EOF'
          mysql:
            default:
              user: root
              host: 127.0.0.1
            replica:
              user: root
              host: 127.0.0.1
          redis:
            host: 127.0.0.1
          cbng:
            enable_user_messaging: false
            enable_irc_messaging: false
          EOF
        if: matrix.target == 'test'

      - name: Run Django tests
        run: |
          poetry run ./manage.py collectstatic
          poetry run ./manage.py test
        if: matrix.target == 'test'

      - name: Run tox target
        run: poetry run tox --current-env -e ${{ matrix.target }}
        if: matrix.target != 'test'

  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build container
        run: |
          docker run \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $PWD:/workspace -w /workspace \
            buildpacksio/pack build reviewer --builder heroku/builder:24
