name: Release
on: { push: { tags: [ 'v*' ], branches: [ main ] } }
permissions:
  deployments: write
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Package the source
        run: |
          tar -cvf reviewer.tar.gz *

      - name: Crease a release
        uses: ncipollo/release-action@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          artifacts: "reviewer.tar.gz"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cluebotng/ci-execute-fabric@main
        with:
          task: deploy-reviewer
          release: ${{ github.ref }}
          ssh_key: ${{ secrets.CI_SSH_KEY }}
